# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69aa89c7b7cb5415b90e46c394fba9f9e41ae1f540328ec732e6c527aac6c98c4d07ef8a083f3b24b3869396dd096ac9da667f035bab01b39d0b6a2cc2d94364

test:
  secret_key_base: 77f6f9f96f73c0263d956f04038342713f7c28d00dead004b2822a6b6e18b78c4f16060c8664316005edcde9c96c593d1ad435ea98e087fc2dcfad1c4a81b65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
